---
# For more details please see gitpod.io/docs/references/gitpod.iml
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode

    - vscode.typescript

    - vscode.typescript-language-features

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
